import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React, {useEffect, useRef, useState, useCallback} from 'react'
import styles from '../styles/Home.module.scss'
import Footer from './components/footer';
import { gsap } from "gsap";
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger'

const Home: NextPage = () => {

  gsap.registerPlugin(ScrollTrigger)

  const pagesWrapperRef = useRef<HTMLDivElement | null >(null);
  const pagesRef = useRef<HTMLDivElement | null >(null);
  const didEffect = React.useRef(false);

  const setupGsap = useCallback((pagesElement: HTMLDivElement, pagesWrapperElement: HTMLDivElement) => {
    gsap.to(pagesElement, {
      x: () => -(pagesElement.clientWidth - pagesWrapperElement.clientWidth),
      ease: 'none',
      scrollTrigger: {
        trigger: '#main',
        start: 'top top',
        end: () => `+=${pagesElement.clientWidth - pagesWrapperElement.clientWidth}`,
        scrub: true,
        pin: true,
        anticipatePin: 1,
        invalidateOnRefresh: true,
        // markers:true
      },
    })
  },[])

  useEffect(() => {
    if (didEffect.current) return 
    didEffect.current = true;
    const pagesElement = pagesRef?.current;
    if(!pagesElement) return
    
    const pagesWrapperElement = pagesWrapperRef?.current;
    if(!pagesWrapperElement) return
    setupGsap(pagesElement, pagesWrapperElement)
  }, [setupGsap])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className={styles.section} id="main">
          <div className={styles.container}>
            <div className={styles.pagesWrapper} ref={pagesWrapperRef}>
              <div className={styles.pages} ref={pagesRef}>
                <div className={styles.page}>
                  1
                  <Image width={512} height={640} alt='image' src="https://placehold.jp/512x640.png"/>
                </div>
                <div className={styles.page}>
                  2
                  <Image width={512} height={640} alt='image' src="https://placehold.jp/512x640.png"/>
                </div>
                <div className={styles.page}>
                  3
                  <Image width={512} height={640} alt='image' src="https://placehold.jp/512x640.png"/>
                </div>
                <div className={styles.page}>
                  4
                  <Image width={512} height={640} alt='image' src="https://placehold.jp/512x640.png"/>
                </div>
                <div className={styles.page}>
                  5
                  <Image width={512} height={640} alt='image' src="https://placehold.jp/512x640.png"/>
                </div>
                <div className={styles.page}>
                  6
                  <Image width={512} height={640} alt='image' src="https://placehold.jp/512x640.png"/>
                </div>
                <div className={styles.page}>
                  7
                  <Image width={512} height={640} alt='image' src="https://placehold.jp/512x640.png"/>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      {/* <Footer /> */}
    </div>
  )
}

export default Home
