import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from '../styles/Home.module.scss'
import Footer from './components/footer';

const Home: NextPage = () => {
  return (
    <div className={styles.all}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.pages}>
          <div className={styles.page}>
            <Image width={512} height={640} alt='image' src="https://placehold.jp/512x640.png"/>
          </div>
          <div className={styles.page}>
            <Image width={512} height={640} alt='image' src="https://placehold.jp/512x640.png"/>
          </div>
          <div className={styles.page}>
            <Image width={512} height={640} alt='image' src="https://placehold.jp/512x640.png"/>
          </div>
          <div className={styles.page}>
            <Image width={512} height={640} alt='image' src="https://placehold.jp/512x640.png"/>
          </div>
          <div className={styles.page}>
            <Image width={512} height={640} alt='image' src="https://placehold.jp/512x640.png"/>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}

export default Home
